### ISSUE TITLE
resource_category_spec: needs test coverage

### ISSUE THREAD

**Issue by swearingenmj** [swearingenmj/cs362-coad-resources#6]
resource_category_spec test file has 0 test coverage over its assocaited file models/resource_category.rb

Write tests for:

- Associations (has many tickets, has and belongs to many organizations)
- Validations (blank name, name length, uniqueness)
- Methods (activate, deactivate, inactive?, to_s)
- Attributes (name)
- Unspecified

**Comment by achidester** [comment]
This test file has adequate test coverage as of now.
